# @Gateway_HostAddress = http://localhost:5205
@Gateway_HostAddress = http://localhost:8082

POST {{Gateway_HostAddress}}/users/query
Accept: application/json
Content-Type: application/json

{
  "Sql": "SELECT id, name FROM c WHERE name = 'Matteo1'"
}

###

PUT {{Gateway_HostAddress}}/users
Accept: application/json
Content-Type: application/json

{
  "id": "matteo1",
  "name": "Matteo1",
  "city": "Asolo"
}

###

PUT {{Gateway_HostAddress}}/users
Accept: application/json
Content-Type: application/json

{
  "id": "matteo2",
  "name": "Matteo2",
  "city": "Asolo"
}

###

GET {{Gateway_HostAddress}}/users/matteo
Accept: application/json
