networks:
  db_network:
    driver: bridge

services:
  gateway:
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    container_name: db_gateway
    networks:
      - db_network
    ports:
      - "8082:8080"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
